spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://goditer.cd1lzbyeyukd.ap-northeast-2.rds.amazonaws.com:3306/goditer
    username: chisae
    password: dnjswns1142!
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update #서버 실행시에는 update로 변경
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 307045080553-ou8bpgc262vfu44bud1ne4qbe0585doc.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://goditerapi.xyz/login/oauth2/code/google
            scope:
              - profile
              - email
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: zV2GZJoWf5RpGhS1nX9cFHoaiLml12pREYOsT4YrTkE=
  expire-length: 31536000000

cors:
  allowed-origin: https://goditer-front.vercel.app

redirect:
  signup-url: https://goditer-front.vercel.app/signup
  home-url : https://goditer-front.vercel.app/main

app:
  database:
    seeding:
      enabled: true

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:bootsecurity.p12
    key-store-password: 46881142
    key-store-type: PKCS12
    key-alias: bootsecurity













